### ISSUE TITLE
Functions roadmap

### ISSUE THREAD

**Issue by TavoNiievez** [Codeception/module-symfony#52]
### Totally new:
- [x] **seeUserHasRoles**: there is already a function that checks a single role `seeUserHasRole`, another is required that allows receiving an array of roles as a parameter. (#80)
- [x] **seeRememberedAuthentication** (#70)
- [x] **dontSeeRememberedAuthentication** (#70)

### From the laravel module:
- [x] **seeFormErrorMessages**: it can be added when `seeFormErrorMessage` is merged. (#67)
- [x] **seeEventTriggered**: Useful when checking the flow of an algorithm against the operation of the Symfony Event/Listener system. (#68)
- [x] **dontSeeEventTriggered**: as a counterpart to the previous one. (#83)
- [x] **grabNumRecords**: to obtain the number of persisted records of a specific Entity. (#72)
- [x] **seeSessionHasValues**: to assert multiple attributes/values in the session. (#73)

## To be modified:

- [x] **seeAuthentication** (#70)
- [x] **dontSeeAuthentication** (#70)
- [x] **persistPermanentService** (#71)

Feel free to request new functions or question the ones mentioned above.

**Comment by TavoNiievez** [comment]
I am closing this as most of the planned features were added.
